-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 09:18:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema videoclub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema videoclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videoclub` DEFAULT CHARACTER SET utf8 ;
USE `videoclub` ;

-- -----------------------------------------------------
-- Table `videoclub`.`caregoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videoclub`.`caregoria` (
  `id` INT(11) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videoclub`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videoclub`.`pelicula` (
  `codigo` INT(11) NOT NULL,
  `precio` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `formato4k` VARCHAR(1) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_pelicula_caregoria_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_pelicula_caregoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `videoclub`.`caregoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'root' IDENTIFIED BY '123456';

GRANT ALL ON `videoclub`.* TO 'root';
GRANT SELECT ON TABLE `videoclub`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER ON TABLE `videoclub`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `videoclub`.* TO 'root';
GRANT EXECUTE ON ROUTINE `videoclub`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
